import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProviderSession from "./ProviderSession";
import Header from "./components/Header";
import { message } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProviderSession>
      <html lang="en" className="dark">
        <body className={"bg-no-repeat bg-blue-600"}>
          <Header />
          {children}
        </body>
      </html>
    </ProviderSession>
  );
}
