# services:
#   nest-api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 4000:4000
#     environment:
#       - NODE_ENV=development
#       - DB_PORT=3306
#       - DB_HOST=mysql_db
#     volumes:
#       - ./src:/usr/src/app/src
#   mysql_db:
#     image: mysql:latest
#     ports:
#       - 3306:3306
#     environment:
#       - MYSQL_ROOT_PASSWORD=admin
#       - MYSQL_DATABASE=qlgl
#     restart: always
#     expose:
#       - 3306
#     command: --default-authentication-plugin=mysql_native_password
version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000' # Map host port 3000 to container port 3000 (NestJS)
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306 # Standard MySQL port
      MYSQL_USERNAME: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: qlgl
    depends_on:
      - mysql
    volumes:
      - ./src:/usr/src/app/src

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: qlgl # Same as above
    volumes:
      - mysql-data:/var/lib/mysql # Persistent storage for MySQL data

volumes:
  mysql-data: {} # Empty volume for MySQL data
